# Generated by Django 4.2.27 on 2026-04-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('discount_percent', models.PositiveSmallIntegerField(default=10, verbose_name='скидка, %')),
                ('starts_at', models.DateTimeField(verbose_name='начало')),
                ('ends_at', models.DateTimeField(verbose_name='окончание')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='product',
            name='storage_tier',
            field=models.CharField(choices=[('standard', 'Обычное хранение'), ('express', 'Ускоренная отгрузка')], default='standard', max_length=20, verbose_name='тип хранения'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_received_at',
            field=models.DateTimeField(blank=True, help_text='В БД хранится момент времени (UTC с учётом USE_TZ). По разнице с текущим моментом (timezone.now()) считаем «сколько дней на складе» для скидок.', null=True, verbose_name='дата поступления на склад'),
        ),
    ]
