# Generated by Django 4.2.27 on 2026-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promotion_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', through='shop.Favorite', to='shop.product', verbose_name='избранные товары'),
        ),
    ]
