# Generated by Django 4.2.27 on 2026-04-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_favorite_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/photos/', verbose_name='фото товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_report',
            field=models.FileField(blank=True, null=True, upload_to='products/reports/', verbose_name='файл проверки качества'),
        ),
    ]
