# Generated by Django 4.2.27 on 2026-04-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_photo_product_quality_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='ссылка на источник'),
        ),
    ]
